version: '3.8'

services:

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
volumes:
  mariadb_volume: {}
